services:
  tekkit-server:
    build: .
    command: >
      java -Dlog4j.configurationFile=log4j2_server.xml -Xmx2G -Xms1G -jar TekkitLegends.jar nogui
    ports:
      - "25565:25565"
    environment:
      - SERVER_OP=acidtib,gopherthegold
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/world:/tekkit/world
