services:
  tekkit-classic-server:
    build: .
    ports:
      - "25565:25565"
    environment:
      - SERVER_OP=minecraft_account_name_here
      - JAVA_ARGS=-Xmx3G -Xms2G
    restart: unless-stopped
    volumes:
      - ./data/world:/minecraft/world
      - ./data/world_nether:/minecraft/world_nether
      - ./data/world_the_end:/minecraft/world_the_end
      - ./data/plugins:/minecraft/plugins
