services:
  tekkit-server:
    build: .
    command: >
      java -Dlog4j.configurationFile=log4j2_server.xml -Xmx4G -Xms2G -jar TekkitLegends.jar nogui
    ports:
      - "25565:25565"
    environment:
      - SERVER_OP=acidtib,gopherthegold
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/world:/tekkit/world
      - ./server.properties:/tekkit/server.properties
