services:
  tekkit-server:
    build: .
    ports:
      - "25565:25565"
    environment:
      - SERVER_OP=acidtib,gopherthegold
      - JAVA_ARGS=-Dlog4j.configurationFile=log4j2_server.xml -Xmx2G -Xms1G -XX:MaxPermSize=128m
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/world:/minecraft/world
